[package]
name = "verification-sdk"
version = "0.1.0"
edition = "2021"
description = "Verification SDK"
license = "MIT"

[dependencies]
tokio = "1.48.0"
reqwest = { version = "0.12.26", features = ["json"] }

serde = "1.0.228"
serde_json = "1.0.145"
base64 = "0.22.1"
hex = "0.4.3"
regex = "1.12.2"

sha2 = "0.10.9"
sha3 = "0.10.8"
k256 = "0.13.4"
ed25519-dalek = "2.2.0"

x509-cert = "0.2.5"
pem-rfc7468 = { version = "1.0.0",features = ["std"] }
tokio-rustls = { version = "0.26.4", default-features = false, features = ["ring"] }
webpki-roots = "1.0.4"

dcap-qvl = "0.3.9"

thiserror = "2.0.17"
anyhow = "1.0.100"
